version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    container_name: api_scraping_app
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["python", "main.py"]

volumes:
  postgres_data:
